# Generated by Django 4.2.26 on 2025-11-13 02:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('category_code', models.CharField(db_index=True, max_length=50)),
                ('category_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(db_index=True, max_length=50)),
                ('district', models.CharField(db_index=True, max_length=50)),
                ('neighborhood', models.CharField(db_index=True, max_length=50)),
                ('detail_address', models.CharField(max_length=200)),
                ('road_address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('like_count', models.IntegerField(default=0)),
                ('kakao_place_id', models.CharField(max_length=50, unique=True)),
                ('operating_information', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '매장',
                'verbose_name_plural': '매장목록',
                'db_table': 'pet_stores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='maps.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜한 장소',
                'verbose_name_plural': '찜한 장소들',
                'db_table': 'like_places',
                'unique_together': {('user', 'store')},
            },
        ),
    ]
