# Generated by Django 4.2.25 on 2025-11-06 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('reason', models.CharField(choices=[('HATE', '혐오 및 차별'), ('INSULT', '욕설 및 비방'), ('ILLEGAL', '불법 정보'), ('SPAM', '스팸 및 홍보성 게시물'), ('PRIVACY', '개인정보 침해'), ('COPYRIGHT', '저작권/지적재산권 침해'), ('YOUTH', '청소년 유해 정보'), ('OTHER', '기타')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', '접수'), ('RESOLVED', '처리완료'), ('REJECTED', '기각')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='report_content_d2ada8_idx'), models.Index(fields=['user', '-created_at'], name='report_user_id_ffd6c6_idx'), models.Index(fields=['status', '-created_at'], name='report_status_9e629c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='uniq_user_target_report'),
        ),
    ]
