# Generated by Django 4.2.25 on 2025-11-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='community_c_post_id_4c58cc_idx',
            old_name='comment_post_id_a800f2_idx',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='community_comment',
        ),
    ]
