# Generated by Django 4.2.25 on 2025-11-06 02:24

from django.db import migrations


def seed_categories(apps, _schema_editor):  # ← _schema_editor 로 경고 제거(아래 2번 참고)
    PostCategory = apps.get_model("posts", "PostCategory")
    for name in ("자유게시판", "정보공유", "질문게시판"):
        PostCategory.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
