# Generated by Django 4.2.25 on 2025-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_seed_post_categories'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('view_count__gte', 0)), name='ck_post_view_count_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('like_count__gte', 0)), name='ck_post_like_count_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('comment_count__gte', 0)), name='ck_post_comment_count_nonneg'),
        ),
    ]
