# Generated by Django 4.2.25 on 2025-11-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='like',
            new_name='community_l_content_846b74_idx',
            old_name='like_content_bc653d_idx',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='community_l_user_id_395c5f_idx',
            old_name='like_user_id_75cfe4_idx',
        ),
        migrations.AlterModelTable(
            name='like',
            table='community_like',
        ),
    ]
